"""QCar model zoo: train every HEAL fusion method on QCar and keep one clean,
loadable checkpoint folder per method. Everything it does is defined in
qcar/zoo.json; this file hardcodes no method, path or checkpoint.

    python qcar/zoo.py configs            # write qcar/configs/zoo/<method>.yaml
    python qcar/zoo.py check [m ...]      # build + init + a few AMP train steps each (catches OOM / key errors)
    python qcar/zoo.py train [m ...]      # sequential queue: train -> eval -> collect; skips finished methods
    python qcar/zoo.py collect <m> <run>  # copy one finished run into the zoo by hand
    python qcar/zoo.py index              # rewrite <checkpoints_dir>/INDEX.md from the collected evals

A collected method folder is directly loadable:
    python qcar/eval.py --model_dir checkpoints/qcar/zoo/<method>
"""
import argparse
import copy
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import time

import yaml

from qcar import config

ZOO_JSON = os.path.join(config.HERE, "zoo.json")
KEEP_FILES = ("config.yaml", "resolved_hypes.json", "run_log.json", "eval_validate.json")


def load_zoo():
    return config.load_conf(ZOO_JSON)


def selected(zoo, names):
    names = names or list(zoo["methods"])
    unknown = [n for n in names if n not in zoo["methods"]]
    if unknown:
        raise SystemExit("unknown method(s) %s; zoo.json defines %s" %
                         (unknown, list(zoo["methods"])))
    return names


def config_path(zoo, name):
    return os.path.join(zoo.path_of("configs_dir"), name + ".yaml")


def read_yaml(path, text_fixes=None):
    with open(config.repo_path(path)) as f:
        text = f.read()
    for old, new in (text_fixes or {}).items():
        if old not in text:
            raise SystemExit("source_text_fixes: %r not found in %s" % (old[:40], path))
        text = text.replace(old, new)
    return yaml.load(text, Loader=yaml.Loader)


def get_by_path(hypes, dotted_key):
    node = hypes
    for part in dotted_key.split("."):
        node = node[part]
    return node


# --------------------------------------------------------------------------
# configs
# --------------------------------------------------------------------------

def build_config(zoo, name):
    method = zoo["methods"][name]
    sensor = method["sensor"]
    if sensor not in zoo["bases"]:
        raise SystemExit("%s: no bases.%s in zoo.json" % (name, sensor))
    base = read_yaml(zoo["bases"][sensor])
    source = read_yaml(method["model_from"], method.get("source_text_fixes"))

    cfg = copy.deepcopy(base)
    cfg["name"] = "QCarZoo_%s" % name
    cfg["model"] = copy.deepcopy(source["model"])
    cfg["model"]["args"].update(method.get("model_args", {}))
    if method.get("loss_from_source"):
        cfg["loss"] = copy.deepcopy(source["loss"])
    for key in method.get("keys_from_source", []):
        config.set_by_path(cfg, key, copy.deepcopy(get_by_path(source, key)))
    if method.get("extra_plugins"):
        cfg["_qcar_plugins"] = (config.split_list(config.load_conf()["plugins"])
                                + list(method["extra_plugins"]))

    if sensor == "camera":
        # QCar camera: 1 front camera, 480x640, no depth ground truth
        ego = cfg["heter"]["ego_modality"]
        base_encoder = base["model"]["args"][ego]["encoder_args"]
        encoder = cfg["model"]["args"][ego]["encoder_args"]
        encoder["data_aug_conf"] = copy.deepcopy(base_encoder["data_aug_conf"])
        encoder["depth_supervision"] = base_encoder["depth_supervision"]
    for key, value in method.get("set", {}).items():
        config.set_by_path(cfg, key, copy.deepcopy(value))

    for key in ("_qcar_pretrained_checkpoint",
                "_qcar_encoder_initialization_checkpoint",
                "_qcar_encoder_initialization_prefixes"):
        cfg.pop(key, None)
    if method["init"] == "full":
        cfg["_qcar_pretrained_checkpoint"] = method["pretrained"]
    elif method["init"] == "encoder":
        cfg["_qcar_pretrained_checkpoint"] = None
        cfg["_qcar_encoder_initialization_checkpoint"] = zoo["encoder_init_checkpoint"][sensor]
        cfg["_qcar_encoder_initialization_prefixes"] = list(zoo["encoder_init_prefixes"])
    else:
        raise SystemExit("%s: init must be 'full' or 'encoder'" % name)
    cfg["_qcar_stage"] = "QCar model zoo: %s (%s), generated by qcar/zoo.py from %s + %s" % (
        name, sensor, zoo["bases"][sensor], method["model_from"])
    return cfg


def cmd_configs(zoo, names):
    os.makedirs(zoo.path_of("configs_dir"), exist_ok=True)
    for name in selected(zoo, names):
        cfg = build_config(zoo, name)
        path = config_path(zoo, name)
        with open(path, "w") as f:
            f.write("# GENERATED by qcar/zoo.py configs -- edit qcar/zoo.json, not this file.\n")
            yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=None)
        print("wrote", os.path.relpath(path, config.REPO_ROOT))


# --------------------------------------------------------------------------
# check
# --------------------------------------------------------------------------

def cmd_check(zoo, names):
    """Same code path as train.py (plugins, registry, weight init, freeze),
    then check_steps AMP forward/backward steps, reporting peak GPU memory."""
    import torch
    from torch.utils.data import DataLoader
    import opencood.hypes_yaml.yaml_utils as yaml_utils
    from opencood.data_utils.datasets import build_dataset
    from opencood.tools import train_utils
    from qcar import registry, train as qtrain

    conf = config.load_conf()
    no_cli = argparse.Namespace(plugins=None, model_packages=None, loss_packages=None)
    results = {}
    dataset = dataset_key = None
    for name in selected(zoo, names):
        print("\n==== check %s ====" % name)
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
        try:
            hypes = yaml_utils.load_yaml(config_path(zoo, name), None)
            config.resolve_modules(no_cli, hypes, conf)
            # labels depend on postprocess (anchor feature_stride), so only
            # reuse the dataset between methods whose data sections match
            data_key = json.dumps([hypes["postprocess"], hypes["preprocess"],
                                   hypes["heter"]], sort_keys=True, default=str)
            if dataset is None or data_key != dataset_key:
                dataset = build_dataset(hypes, visualize=False, train=True)
                dataset_key = data_key
            loader = DataLoader(dataset, batch_size=conf["train_batch_size"], shuffle=True,
                                num_workers=0, collate_fn=dataset.collate_batch_train)
            model = registry.create_model(hypes)
            qtrain.load_initial_weights(hypes, model, len(dataset))
            criterion = registry.create_loss(hypes)
            optimizer = train_utils.setup_optimizer(hypes, model)
            model.cuda().train()
            use_amp = "--no_amp" not in zoo["methods"][name].get("train_flags", [])
            scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
            started = time.time()
            steps = 0
            for batch in loader:
                batch = train_utils.to_device(batch, torch.device("cuda"))
                batch["ego"]["epoch"] = 0
                with torch.cuda.amp.autocast(enabled=use_amp):
                    out = model(batch["ego"])
                    loss = criterion(out, batch["ego"]["label_dict"])
                    if hypes["model"]["args"].get("supervise_single", False):
                        loss = loss + criterion(out, batch["ego"]["label_dict_single"],
                                                suffix="_single")
                scaler.scale(loss).backward()
                scaler.step(optimizer); scaler.update(); optimizer.zero_grad()
                steps += 1
                if steps >= zoo["check_steps"]:
                    break
            peak = torch.cuda.max_memory_allocated() / 2 ** 30
            results[name] = "OK   loss %.3f  peak %.2f GiB  %.2fs/step" % (
                loss.item(), peak, (time.time() - started) / steps)
        except Exception as err:  # report and continue with the next method
            results[name] = "FAIL %s: %s" % (type(err).__name__, str(err).splitlines()[0][:150])
        finally:
            model = optimizer = criterion = out = loss = scaler = None
            torch.cuda.empty_cache()
        print(results[name])
    print("\n==== summary ====")
    for name, line in results.items():
        print("%-11s %s" % (name, line))
    return results


# --------------------------------------------------------------------------
# train / collect / index
# --------------------------------------------------------------------------

def method_dir(zoo, name):
    return os.path.join(zoo.path_of("checkpoints_dir"), name)


def is_done(zoo, name):
    d = method_dir(zoo, name)
    return (bool(glob.glob(os.path.join(d, "net_epoch_bestval_at*.pth")))
            and os.path.isfile(os.path.join(d, "eval_validate.json")))


def run_logged(cmd, log_path):
    print("$", " ".join(cmd), ">", os.path.relpath(log_path, config.REPO_ROOT))
    with open(log_path, "a") as log:
        log.write("\n$ %s\n" % " ".join(cmd))
        log.flush()
        return subprocess.call(cmd, stdout=log, stderr=subprocess.STDOUT,
                               cwd=config.REPO_ROOT)


def run_dir_from_log(log_path):
    with open(log_path) as f:
        found = re.findall(r"run_log\.json in: (.+)", f.read())
    return found[-1].strip() if found else None


def cmd_collect(zoo, name, run_dir):
    run_dir = os.path.abspath(run_dir)
    best = sorted(glob.glob(os.path.join(run_dir, "net_epoch_bestval_at*.pth")))
    if not best:
        raise SystemExit("%s: no net_epoch_bestval_at*.pth in %s" % (name, run_dir))
    dest = method_dir(zoo, name)
    os.makedirs(dest, exist_ok=True)
    for old in glob.glob(os.path.join(dest, "net_epoch_bestval_at*.pth")):
        os.remove(old)
    shutil.copy2(best[-1], dest)
    for fname in KEEP_FILES:
        src = os.path.join(run_dir, fname)
        if os.path.isfile(src):
            shutil.copy2(src, dest)
    with open(os.path.join(dest, "SOURCE_RUN.txt"), "w") as f:
        f.write("trained run: %s\nconfig: %s\n" % (
            os.path.relpath(run_dir, config.REPO_ROOT),
            os.path.relpath(config_path(zoo, name), config.REPO_ROOT)))
    print("collected %s -> %s" % (name, os.path.relpath(dest, config.REPO_ROOT)))


def cmd_index(zoo):
    rows = []
    iou = config.load_conf()["eval_iou_thresh"]
    for name, method in zoo["methods"].items():
        d = method_dir(zoo, name)
        ev_path = os.path.join(d, "eval_validate.json")
        if not os.path.isfile(ev_path):
            rows.append("| %s | %s | %s | - | - | - | not trained yet |" % (
                name, method["sensor"], method["init"]))
            continue
        ev = json.load(open(ev_path))
        iou = ev["iou_thresh"]
        best = sorted(glob.glob(os.path.join(d, "net_epoch_bestval_at*.pth")))
        rows.append("| %s | %s | %s | %.4f | %.4f | %d / %d | `%s` |" % (
            name, method["sensor"], method["init"], ev["average_precision"], ev["recall_at_iou"],
            ev["true_positives"], ev["false_positives"],
            os.path.basename(best[-1]) if best else "?"))
    text = "\n".join([
        "# QCar model zoo",
        "",
        "Generated by `python qcar/zoo.py index` from each method's `eval_validate.json`.",
        "Same data and training recipe for every method (`%s`), validate split, IoU %s." % (
            ", ".join(zoo["bases"].values()), iou),
        "Development numbers only: CoopFront has no independent test trajectory.",
        "",
        "Load any of them: `python qcar/eval.py --model_dir checkpoints/qcar/zoo/<method>`",
        "",
        "| method | sensor | init | AP | recall | TP / FP | checkpoint |",
        "|---|---|---|---|---|---|---|",
    ] + rows) + "\n"
    path = os.path.join(zoo.path_of("checkpoints_dir"), "INDEX.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print(text)


def cmd_train(zoo, names):
    logs = zoo.path_of("logs_dir")
    os.makedirs(logs, exist_ok=True)
    py = sys.executable
    for name in selected(zoo, names):
        if is_done(zoo, name):
            print("skip %s (already in the zoo)" % name)
            continue
        log_path = os.path.join(logs, name + ".log")
        started = time.time()
        code = run_logged([py, "qcar/train.py", "-y", config_path(zoo, name)]
                          + list(zoo["methods"][name].get("train_flags", [])), log_path)
        run_dir = run_dir_from_log(log_path)
        if code != 0 or not run_dir:
            print("FAILED %s (exit %s) -- see %s; continuing" % (name, code, log_path))
            continue
        code = run_logged([py, "qcar/eval.py", "--model_dir", run_dir,
                           "--split", "validate"], log_path)
        if code != 0:
            print("FAILED eval %s -- see %s; continuing" % (name, log_path))
            continue
        cmd_collect(zoo, name, run_dir)
        cmd_index(zoo)
        print("%s done in %.1f h" % (name, (time.time() - started) / 3600))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["configs", "check", "train", "collect", "index"])
    ap.add_argument("args", nargs="*", help="method names (default: all in zoo.json); "
                                            "for collect: <method> <run_dir>")
    opt = ap.parse_args()
    os.chdir(config.REPO_ROOT)
    zoo = load_zoo()
    if opt.command == "configs":
        cmd_configs(zoo, opt.args)
    elif opt.command == "check":
        cmd_check(zoo, opt.args)
    elif opt.command == "train":
        cmd_train(zoo, opt.args)
    elif opt.command == "collect":
        if len(opt.args) != 2:
            raise SystemExit("collect needs <method> <run_dir>")
        cmd_collect(zoo, opt.args[0], opt.args[1])
        cmd_index(zoo)
    else:
        cmd_index(zoo)


if __name__ == "__main__":
    main()
